const phases = [
  {
    phase:'one',
    allResidents:'65+',
    foodService:'Open at 1/2 Capacity',
    Venues:'Closed',
    retail:'Open at 1/2 Capcity',
    salons:'Closed',
    health:'Routine and Elective for ages under 70',
    fitness:'Closed',
    parks:'Closed',
    sportsVenues:'Closed',
  },
  {
    phase: 'two',
    allResidents:'',
    foodService:'',
    Venues:'',
    retail:'',
    salons:'',
    health:'',
    fitness:'',
    parks:'',
    sportsVenues:'',
  },
  {
    phase: 'three',
    allResidents:'',
    foodService:'',
    Venues:'',
    retail:'',
    salons:'',
    health:'',
    fitness:'',
    parks:'',
    sportsVenues:'',
  },
  {
    phase: 'four',
    allResidents:'',
    foodService:'',
    Venues:'',
    retail:'',
    salons:'',
    health:'',
    fitness:'',
    parks:'',
    sportsVenues:'',
  },
]
